name: Daily NBA Pull

on:
  schedule:
    # 0 6 * * * = 6 AM UTC â†’ 1 AM ET
    - cron: "0 6 * * *"
  workflow_dispatch: # allows manual run

jobs:
  call-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Call pull_nba_games
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          https://deqmlxmmruiuitwpiyud.supabase.co/functions/v1/pull_nba_games

      - name: Call fetch_fantasy_stats
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          https://deqmlxmmruiuitwpiyud.supabase.co/functions/v1/fetch-fantasy-stats
