name: Live NBA Scores

on:
  schedule:
    # every 5 minutes, 24/7
    - cron: "*/5 * * * *"
  workflow_dispatch: # allows manual trigger anytime

jobs:
  live-scores:
    runs-on: ubuntu-latest
    steps:
      - name: Update Live NBA Game Scores
        run: |
          echo "Calling update_live_game_scores..."
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          https://deqmlxmmruiuitwpiyud.supabase.co/functions/v1/update_live_game_scores
